### ISSUE TITLE
Urgency for dependent services

### ISSUE THREAD

**Issue by gseyerl** [TiVo/terraform-provider-splunk-itsi#119]
Hi,
we are still happily using your provider. Thanks again.

Within the GUI, it is possible to define Urgencys on dependent KPIs (e.g. Service Health Scores) for service objects.

I think the REST API pendant is the setting overloaded_urgencies. 

    "services_depends_on": [
     {
        "kpis_depending_on": [
          "SHKPI-2d4c4f4e-dfd9-4e0b-b49f-39739cebe782"
        ],
        "serviceid": "2d4c4f4e-dfd9-4e0b-b49f-39739cebe782",
        "overloaded_urgencies": {
          "SHKPI-2d4c4f4e-dfd9-4e0b-b49f-39739cebe782": 1
        }
      },
      {
        "kpis_depending_on": [
          "SHKPI-ebccf70a-de1e-47a7-82c4-6bd607a7c6a6"
        ],
        "serviceid": "ebccf70a-de1e-47a7-82c4-6bd607a7c6a6",
        "overloaded_urgencies": {
          "SHKPI-ebccf70a-de1e-47a7-82c4-6bd607a7c6a6": 11
        }
      }

Although, I did not find those settings anywhere in the sheer endless labyrinths of the Splunk Documentation, it would be really great if you could include those settings in your provider.

Best
G

**Comment by benoittoulme** [comment]
The team reviewed the request and that looks easy to implement. We should be able to do that in the next few days.

**Comment by dmitrykruglov** [comment]
Hi @gseyerl,

this feature has been implemented in #121 , and should be available in the new v0.10.4 provider release.

**Comment by benoittoulme** [comment]
Thank you @dmitrykruglov !
You can find also the reference in the provider docs: https://registry.terraform.io/providers/TiVo/splunk-itsi/latest/docs/resources/service#overloaded_urgencies
