### ISSUE TITLE
Multi-value entity info fields not being set correctly.

### ISSUE THREAD

**Issue by klunkeh** [TiVo/terraform-provider-splunk-itsi#200]
Hi there,

### Terraform Version
1.15

### Expected Behavior
When submitting a comma separated info field for an entity, this should be represented as two separate values. When viewing in the GUI, it looks as it should.

### Actual Behavior
A comma separated value is passed as a single value. This breaks the entity matching against a service. If you open the entity in the GUI and click save, this is automatically corrected. You can see the the screenshot that after this is done, it matches the service it was meant to match against.

You can view the correction that occurs by calling the entity endpoint (http://ip:8089/servicesNS/nobody/SA-ITOA/itoa_interface/entity) after running a terraform apply, and then again after opening the entity in gui and saving.

![image](https://github.com/TiVo/terraform-provider-splunk-itsi/assets/2231825/845c962f-0ac6-4fc8-a316-f2d532bbf39e)

### Terraform Data Source
Here is an example data source and resource that will replicate the issue.

```hcl
data "itsi_splunk_search" "itsi_entity_search" {

    search {
      query         = <<-EOT
  | makeresults
  | streamstats count 
  | eval host = case(count=1, "server22")
  | eval phost = case(count=1, "server13")
  | eval environment = case(count=1, "Example.Environment")
  | eval role = case(count=1, "Example.Role.1,Example.Role.2")
  | eval etype = case(count=1, "Windows")
  | table host phost environment etype role
      EOT
      earliest_time = "-15m"
    }
  
    join_fields = ["host"]
  }
```

```hcl
resource "itsi_entity" "import_entities" {
  for_each = { for entity in data.itsi_splunk_search.itsi_entity_search.results : entity["host"] => entity }

  title = each.key
  aliases = {
    "entity_name"    = each.key
    "itsi_entity_id" = each.key
    "host"           = each.key
  }
  info = {
    "phost"       = each.value["phost"]
    "role"        = try(each.value["role"], "unknown")
    "environment" = each.value["environment"]
  }

  entity_type_ids = [each.value["etype"]]
}

```

**Comment by masha1997** [comment]
Hi @klunkeh, 
Could you, please, check with v0.11.2, the issue should be fixed via https://github.com/TiVo/terraform-provider-splunk-itsi/pull/203/files

**Comment by klunkeh** [comment]
Hi @masha1997, can confirm this is now working, thank you so much!
