### ISSUE TITLE
Implementing Service Mappings Difficulty

### ISSUE THREAD

**Issue by klunkeh** [TiVo/terraform-provider-splunk-itsi#215]
Hi there

I am currently working on mapping service dependencies and feel like I am stuck in a chicken/egg scenario. I just wanted to reach out to see what the possibility would be of providing a data source for being able to retrieve a shkpi_id and the id of a service, based on a title passed in, similar to the 'itsi_kpi_threshold_template ' data source. However, I am not even sure that will work. Let me explain.

For a bit of brief background, the environment I have is comprised of many hundreds of servers and microservices. 

I have read through the getting-started guide and splunk-itsi_service resource, but I cannot seem to understand how it will functionally work. I can see create a kv collection and populate with the various ids that I would need for service 
dependencies, but then the list will only be populated at the end of the terraform run. In your example, you link all leaf services to your root, but my environment is obviously a little different to the example.

To get access to the to the shkpi_id and the service_id, my only thought that is after the first run to populate the kv collection, a second run would then be able to do a lookup. This would require the module used to create the service too perform a lookup on the first run and if null leave it empty, else populate with the data from the lookup.

Maybe I am fundamentally misunderstanding how this will all work. Would very much appreciate some advise on how to implement this.

I appreciate this may not be the best channel to discuss this so if there is a better way, please let me know.

**Comment by dmitrykruglov** [comment]
Hi @klunkeh,
Based on your description, I understand you are experiencing challenges with linking service dependencies, but it's not exactly clear why. If your leaf services are managed by Terraform within the same project, you should be able to access both the service and shkpi IDs and link them to the root as shown in the "Getting Started" guide. If the leaf services are not managed within the same Terraform project, you can input them externally through several methods, by using terraform data sources or variables, for example:
* You can use a splunk search / `itsi_splunk_search` data source to query them from a collection, that is populated by other means.
* If leaf services are defined in a different terraform project, you can potentially get them from its terraform state using `terraform_remote_state` data source.
If you have a very complex infrastructure, it may make sense to design your terraform solution such that you have 1 or more projects that create just the leaf service nodes, and a separate terraform project to link those leaf nodes to their root.
