### ISSUE TITLE
Error: Splunk search failed: EOF

### ISSUE THREAD

**Issue by premadhas** [TiVo/terraform-provider-splunk-itsi#223]
Hi there,

I'm trying to run a simple test search using this provider and it's throwing below error, can you please help identify where and what I'm missing?
The same query if run directly on the Splunk i'm getting result.

## Error
``` 
> terraform plan
data.itsi_splunk_search.itsi_test_search: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Splunk search failed: EOF
│ 
│   with data.itsi_splunk_search.itsi_test_search,
│   on data.tf line 1, in data "itsi_splunk_search" "itsi_test_search":
│    1: data "itsi_splunk_search" "itsi_test_search" {
```

## not_working.tf
```
data "itsi_splunk_search" "itsi_test_search" {
  
  search {
    query = <<-EOT
      | mstats count(*) WHERE index="*metrics*" span=100ms
    EOT

    earliest_time = "-5m"
  }
}

output "search_data" {
    value = data.itsi_splunk_search.itsi_test_search.results
}
```

## working.tf
```
data "itsi_splunk_search" "test_search" {

  search {
    query = <<-EOT
       | makeresults count=5 | eval test = "A"
    EOT

    earliest_time = "-10m"
  }

  search {
    query = <<-EOT
      | makeresults count=5 | eval test = "B"
    EOT

    earliest_time = "-10m"
  }

}
```

**Comment by dmitrykruglov** [comment]
Hi @premadhas ,

this is similar to #201, and should've been fixed in the beta release.
Please let us know if you still have this problem using the [v1.0.0-beta.5](https://github.com/TiVo/terraform-provider-splunk-itsi/releases/tag/v1.0.0-beta.5) release of the provider.

Thanks

**Comment by premadhas** [comment]
Hi @dmitrykruglov ,

Thanks, upgrading the version fixed the issue.

Thanks
