### ISSUE TITLE
ITSI Service Template

### ISSUE THREAD

**Issue by gseyerl** [TiVo/terraform-provider-splunk-itsi#76]
Hi there,
thank you for this splunk itsi provider. 

We were trying to create some services with this provider in Splunk ITSI.

What we miss at this point, is the possibility to define and reuse service templates.

Are there any plans on including them as well?

Best regards
G

**Comment by benoittoulme** [comment]
Hi @gseyerl. Thank you for using the provider!

We have no plans to implement the resource for the service template at the moment. There are several reasons for this. We did use service templates in the past, but we realized we do not need them with terraform managed resources.

- Services templates modify services, but we want to manage services via terraform. Therefore, using a service template would create drift in the terraform plans.
- Services Templates are buggy. Each time we update one, the dependent services get their thresholds busted and have to be recalculated. This does not happen when defining services directly via terraform.
- Terraform is now our service template. We define KPI base searches, threshold templates, and link them together in KPIs by defining services. So we do not see a reason to use a service template resource, when terraform does the job.
- Service Templates are limited. We sometimes had a service that is dependent on a service template, but for which the threshold defined for a KPI does not match the data specific to the service. In that case, the only solution would be to break the service out of the service template, or risk to have the threshold override reverted whenever someone would update the service template. With Terraform, we define services directly, and therefore we are able to write into config-as-code, such case.

I hope that helps you understanding the reasons for us not using service templates.

**Comment by gseyerl** [comment]
Hi @benoittoulme,
thank you for the detailed answer. After digging into your provider and using it in greater depht, we are now using it, exactly the way you are describing in point three. It works pretty smooth.

You are right, the service template seems like a half broken crutch for web UI users.

Great work. Thank you.

Ciao
G
