### ISSUE TITLE
Missing field_type for service entity_rule definition

### ISSUE THREAD

**Issue by gseyerl** [TiVo/terraform-provider-splunk-itsi#77]
Hi there,

### Terraform Version
Terraform v1.2.8
on linux_amd64

### Affected Resource(s)
Please list the resources as a list, for example:
- itsi_service

It is not possible to define a field_type = "entity_type"  within entity_rules, although entity_type is a valid field type in Splunk ITSI.

 Error: expected entity_rules.0.rule.1.field_type to be one of [alias info title], got entity_type

Thank you
G

**Comment by benoittoulme** [comment]
we released a fix: https://github.com/TiVo/terraform-provider-splunk-itsi/releases/tag/v0.9.5

**Comment by gseyerl** [comment]
Great. Thank you.
